import { 
  Star, 
  Cpu, 
  Database, 
  Cloud, 
  Terminal, 
  Monitor, 
  Brain, 
  Radio, 
  Smartphone, 
  Activity, 
  Code, 
  Zap, 
  Server, 
  Flame, 
  Layers, 
  Smile, 
  Compass, 
  Clock, 
  Search, 
  GitBranch, 
  Settings, 
  Volume2, 
  VolumeX, 
  Play, 
  Mic, 
  Gamepad2, 
  Music, 
  Palette,
  Sparkles
} from 'lucide-react';

export const REGISTERED_PROVIDERS_STATIC_DATA = [
  // --- CHAT TAB ---
  { id: 'official_chat', tab: 'chat', name: 'Official Provider (Local Module)', desc: 'Autonomous local intelligence module. Uses local routing or falls back to offline Markov cognitive state.', pricing: 'free', deployment: 'local', icon: Star, url: 'local' },
  { id: 'gemini', tab: 'chat', name: 'Google Gemini', desc: 'Default thinking core of Yuihime. Direct Google AI Studio SDK.', pricing: 'free', deployment: 'cloud', icon: Sparkles, url: 'gemini.google.com' },
  { id: 'openai', tab: 'chat', name: 'OpenAI / compatible', desc: 'Standard GPT-4o, GPT-4o-mini and OpenAI-compatible instances. Core connector.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'anthropic', tab: 'chat', name: 'Anthropic Claude', desc: 'Claude series models (Sonnet, Opus) reasoning powers.', pricing: 'paid', deployment: 'cloud', icon: Brain, url: 'anthropic.com' },
  { id: 'openrouter', tab: 'chat', name: 'OpenRouter AI', desc: 'Universal gateway for models. Highly customizable list.', pricing: 'paid', deployment: 'cloud', icon: Cpu, url: 'openrouter.ai' },
  { id: 'deepseek', tab: 'chat', name: 'DeepSeek AI', desc: 'High-performance reasoner models from DeepSeek. Highly precise.', pricing: 'paid', deployment: 'cloud', icon: Brain, url: 'deepseek.com' },
  { id: 'groq', tab: 'chat', name: 'Groq Engine', desc: 'Groq LPU powered real-time split-second text generation.', pricing: 'paid', deployment: 'cloud', icon: Zap, url: 'groq.com' },
  { id: 'ollama', tab: 'chat', name: 'Local Ollama', desc: 'Run modern LLMs (Llama 3, Mistral) entirely Offline.', pricing: 'free', deployment: 'local', icon: Terminal, url: 'ollama.ai' },
  { id: 'puter-neural-provider', tab: 'chat', name: 'Puter Cloud Provider', desc: 'Lightweight in-process Puter.js AI interface supporting 500+ model selections. Handles extreme low-latency chats natively.', pricing: 'free', deployment: 'cloud', icon: Cpu, url: 'puter.com' },
  { id: 'custom', tab: 'chat', name: 'Custom Provider', desc: 'Configure custom API Base URL, keys, and endpoints for external or proprietary OpenAI-compatible gateways.', pricing: 'free', deployment: 'cloud', icon: Radio, url: 'custom' },

  // --- SPEECH TAB ---
  { id: 'official_speech', tab: 'speech', name: 'Official Speech Provider', desc: 'Official text-to-speech redirected to local inference module.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'local/speech' },
  { id: 'official_streaming_speech', tab: 'speech', name: 'Official Streaming Speech Provider', desc: 'Official low-latency text-to-speech redirected to local inference module.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'local/streaming' },
  { id: 'none_speech', tab: 'speech', name: 'None', desc: 'No vocal audio output syntheses.', pricing: 'free', deployment: 'local', icon: VolumeX, url: 'none' },
  { id: 'browser_speech', tab: 'speech', name: 'Browser (Local)', desc: 'https://github.com/moeru-ai/xsai-transformers', pricing: 'free', deployment: 'local', icon: Play, url: 'browser' },
  { id: 'gemini_speech', tab: 'speech', name: 'Google Gemini Speech', desc: 'Google Gemini 2.0/3.0 high-fidelity emotive vocal rendering.', pricing: 'free', deployment: 'cloud', icon: Radio, url: 'ai.google.dev' },
  { id: 'openai_speech', tab: 'speech', name: 'OpenAI', desc: 'Standard openai tts and tts-1-hd cloud vocal templates.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'openai_compatible_speech', tab: 'speech', name: 'OpenAI Compatible', desc: 'OpenAI Compatible speech synthesis proxy endpoints.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'openai-compatible' },
  { id: 'elevenlabs', tab: 'speech', name: 'ElevenLabs', desc: 'Sleek vocal synthesis. Advanced high-fidelity voice profiles.', pricing: 'paid', deployment: 'cloud', icon: Volume2, url: 'elevenlabs.io' },
  { id: 'deepgram_speech', tab: 'speech', name: 'Deepgram', desc: 'Super-low latency Deepgram Aura text-to-speech synthesizer.', pricing: 'paid', deployment: 'cloud', icon: Mic, url: 'api.deepgram.com' },
  { id: 'azure_speech', tab: 'speech', name: 'Microsoft / Azure Speech', desc: 'Highly reliable Azure cognitive text-to-speech engine.', pricing: 'paid', deployment: 'cloud', icon: Cloud, url: 'speech.microsoft.com' },
  { id: 'bilibili_index_tts', tab: 'speech', name: 'Bilibili / IndexTTS', desc: 'https://index-tts.github.io/ open source vocal backend.', pricing: 'free', deployment: 'cloud', icon: Music, url: 'index-tts.github.io' },
  { id: 'alibaba_studio_speech', tab: 'speech', name: 'Alibaba Cloud Model Studio', desc: 'Alibaba CosyVoice high-fidelity voice cloned outputs.', pricing: 'paid', deployment: 'cloud', icon: Layers, url: 'bailian.console.aliyun.com' },
  { id: 'volcano_speech', tab: 'speech', name: 'Volcano Engine', desc: 'Bytedance Volcano text-to-speech engine outputs.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'volcengine.com' },
  { id: 'minimax_speech', tab: 'speech', name: 'MiniMax Speech', desc: 'MiniMax highly expressive vocal models syntheses.', pricing: 'paid', deployment: 'cloud', icon: Smile, url: 'minimax.io' },
  { id: 'openrouter_speech', tab: 'speech', name: 'OpenRouter', desc: 'Synthesize voice using openrouter-supported integrations.', pricing: 'paid', deployment: 'cloud', icon: Cpu, url: 'openrouter.ai' },
  { id: 'xiaomi_mimo_speech', tab: 'speech', name: 'Xiaomi MiMo', desc: 'MiMo sound systems Cloud TTS.', pricing: 'paid', deployment: 'cloud', icon: Smartphone, url: 'api.xiaomimimo.com' },
  { id: 'comet_api_speech', tab: 'speech', name: 'Comet API', desc: 'CometAPI audio stream creation endpoints.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'CometAPI.com' },
  { id: 'player2_speech', tab: 'speech', name: 'Player2', desc: 'Gaming voice and custom player styles.', pricing: 'paid', deployment: 'cloud', icon: Gamepad2, url: 'player2.game' },
  { id: 'kokoro_local', tab: 'speech', name: 'Kokoro TTS (Local)', desc: 'Local high quality text-to-speech using lighter Kokoro-82M.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'kokoro-local' },
  { id: 'puter-tts', tab: 'speech', name: 'Puter TTS (Cloud)', desc: 'Cloud-based text-to-speech powered natively by Puter.js Infrastructure.', pricing: 'free', deployment: 'cloud', icon: Play, url: 'puter.com' },
  { id: 'custom_api_speech', tab: 'speech', name: 'Custom AI TTS (Local/Web)', desc: 'Configure custom HTTP GET/POST endpoints (RVC, GPT-SoVITS, Web-TTS, or localhost).', pricing: 'free', deployment: 'local', icon: Radio, url: 'custom-tts' },

  // --- TRANSCRIPTION TAB ---
  { id: 'browser_hearing', tab: 'transcription', name: 'Browser (Local)', desc: 'https://github.com/moeru-ai/xsai-transformers web hearing.', pricing: 'free', deployment: 'local', icon: Play, url: 'browser' },
  { id: 'openai_whisper', tab: 'transcription', name: 'OpenAI', desc: 'Whisper 1 cloud-based voice transcription helper.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'openai_compatible_transcription', tab: 'transcription', name: 'OpenAI Compatible', desc: 'Send audio packets to compatible custom Whisper API gateways.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'openai-compatible' },
  { id: 'aliyun_nls_transcription', tab: 'transcription', name: 'Aliyun NLS', desc: 'Alibaba Aliyun Natural Language Transcription service.', pricing: 'paid', deployment: 'cloud', icon: Layers, url: 'aliyun-nls' },
  { id: 'web_speech_api', tab: 'transcription', name: 'Web Speech API', desc: 'Browser-native STT (requires Chrome/Edge/Safari support).', pricing: 'free', deployment: 'local', icon: Mic, url: 'web-speech' },
  { id: 'comet_api_transcription', tab: 'transcription', name: 'Comet API', desc: 'CometAPI speech synthesis and transcribe streams.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'CometAPI.com' },
  { id: 'xiaomi_mimo_transcription', tab: 'transcription', name: 'Xiaomi MiMo', desc: 'Audit streams and text mapping in MiMo cloud.', pricing: 'paid', deployment: 'cloud', icon: Smartphone, url: 'api.xiaomimimo.com' },

  // --- ARTISTRY TAB ---
  { id: 'comfyui', tab: 'artistry', name: 'ComfyUI', desc: 'Local image generation runner. SD & FLUX node paths.', pricing: 'free', deployment: 'local', icon: Palette, url: '127.0.0.1:8188' },
  { id: 'replicate', tab: 'artistry', name: 'Replicate', desc: 'Hosted diffusion & machine learning cloud pipelines.', pricing: 'paid', deployment: 'cloud', icon: Activity, url: 'replicate.com' },
  { id: 'nano_banana', tab: 'artistry', name: 'Nano Banana', desc: 'AIRI and Google AI Studio Image Preview visual service.', pricing: 'free', deployment: 'cloud', icon: Monitor, url: 'nano-banana' }
];
